### ISSUE TITLE
:Before :After Content

### ISSUE THREAD

**Issue by Vanatis** [FishingCactus/litehtml#56]
The default behaviour for :before and :after is not complient with the litehtml version.

Default:
If content is set to an image url, it shows the image.

Litehtml:
If content is set to an image url, it shows nothing.

**Comment by NuclearCookie** [comment]
can you attach a test script please?

**Comment by crazyjul** [comment]
Set the content with a url like this :

.test:before{
  Content: url( myimage.png );
}

**Comment by NuclearCookie** [comment]
Tested with this:

``` html
<html>
<head>
    <style>
        .test:before{
            content: url('5406614.png');
        }
        .test{
            background-color: red;
            width: 20%;
            height: 20%;
            left: 50%;
            position: absolute;
        }
        .test:after{
            content: url('5406614.png');
        }
    </style>
</head>
<body>
    <div class="test">
        <p>tiededie
        </p>
        <p>tiededie
        </p>
        <p>tiededie
        </p>
    </div>
</body>
</html>
```

And this works the same in chrome as in litehtml. Any idea what the actual issue is? :)

**Comment by Vanatis** [comment]
Cannot reproduce original bug. Everything seems to work fine now.
